### ISSUE TITLE
Exception: Read access from event dispatch thread ...

### ISSUE THREAD

**Issue by Stefku** [ziolko/intellij-javascript-symbols#11]
Version:  2.3

I got an exception. Unfortunately I cannot reproduce it.

```
Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
```

```
Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[ApplicationImpl pooled thread 51,4,Idea Thread Group] 710788316
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 2016.1.1#IU-145.597.3 IDEA, eap:false, os:Windows 7 6.1, java-version:Oracle Corporation 1.8.0_74-b02,6,main] 1938559669
java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:138)
    at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1054)
    at com.intellij.psi.impl.source.PsiFileImpl.d(PsiFileImpl.java:182)
    at com.intellij.psi.impl.source.PsiFileImpl.calcTreeElement(PsiFileImpl.java:799)
    at com.intellij.psi.impl.source.PsiFileImpl.getNode(PsiFileImpl.java:1004)
    at com.intellij.psi.impl.source.PsiFileImpl.acceptChildren(PsiFileImpl.java:820)
    at com.webstorm.symbols.angular.AngularSymbolUtils.getAngularDirectivesInFile(AngularSymbolUtils.java:120)
    at com.webstorm.symbols.angular.AngularSymbolUtils.getInjectedAngularPsiFiles(AngularSymbolUtils.java:63)
    at com.webstorm.symbols.angular.AngularSymbolReferencesSearch.processPsiFileWithInjectedAngularDirectives(AngularSymbolReferencesSearch.java:81)
    at com.webstorm.symbols.angular.AngularSymbolReferencesSearch.processQuery(AngularSymbolReferencesSearch.java:38)
    at com.webstorm.symbols.angular.AngularSymbolReferencesSearch.processQuery(AngularSymbolReferencesSearch.java:24)
    at com.intellij.openapi.application.QueryExecutorBase.execute(QueryExecutorBase.java:79)
    at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:45)
    at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:75)
    at com.intellij.util.UniqueResultsQuery.process(UniqueResultsQuery.java:66)
    at com.intellij.util.UniqueResultsQuery.forEach(UniqueResultsQuery.java:56)
    at com.intellij.find.findUsages.FindUsagesHandler.processElementUsages(FindUsagesHandler.java:126)
    at com.webstorm.symbols.findUsages.MyFindUsagesHandler.processElementUsages(MyFindUsagesHandler.java:21)
    at com.intellij.find.findUsages.FindUsagesManager$2.generate(FindUsagesManager.java:376)
    at com.intellij.usages.impl.SearchForUsagesRunnable.searchUsages(SearchForUsagesRunnable.java:346)
    at com.intellij.usages.impl.SearchForUsagesRunnable.run(SearchForUsagesRunnable.java:325)
    at com.intellij.usages.impl.UsageViewManagerImpl$1.run(UsageViewManagerImpl.java:131)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:369)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)

```

**Comment by Stefku** [comment]
A hint: Right now, the exception occurred at finding usages. But not always.

**Comment by ziolko** [comment]
Hi Stefku,

Thanks for reporting this. I've added a "read action" so in next version it will be fixed. That's unfortunate that these errors appear only sometimes.

Mateusz
