### ISSUE TITLE
Exception: Read access is allowed from event dispatch thread

### ISSUE THREAD

**Issue by ThomasR** [ziolko/intellij-javascript-symbols#6]
I got the following error:

``` plain
Read access is allowed from event dispatch thread or inside read-action only (see com.intellij.openapi.application.Application.runReadAction())
Details: Current thread: Thread[ApplicationImpl pooled thread 20,4,Idea Thread Group] 299146940
; dispatch thread: false; isDispatchThread(): false
SystemEventQueueThread: Thread[AWT-EventQueue-0 IDEA 15.0.4#IU-143.2287.1 IDEA, eap:false, os:Windows 7 6.1, java-version:Oracle Corporation 1.7.0_51-b13,6,main] 1878390049
java.lang.Throwable
    at com.intellij.openapi.diagnostic.Logger.error(Logger.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl.assertReadAccessAllowed(ApplicationImpl.java:1055)
    at com.intellij.psi.impl.file.impl.FileManagerImpl.findDirectory(FileManagerImpl.java:437)
    at com.intellij.psi.impl.PsiManagerImpl.findDirectory(PsiManagerImpl.java:197)
    at com.intellij.psi.impl.file.PsiDirectoryImpl.getParentDirectory(PsiDirectoryImpl.java:136)
    at com.intellij.psi.impl.file.PsiDirectoryImpl.getParent(PsiDirectoryImpl.java:232)
    at com.intellij.psi.impl.file.PsiDirectoryImpl.getParent(PsiDirectoryImpl.java:55)
    at com.webstorm.symbols.SymbolUtils.getJSLiteraExpression(SymbolUtils.java:84)
    at com.webstorm.symbols.reference.SymbolReferencesSearch.processQuery(SymbolReferencesSearch.java:26)
    at com.webstorm.symbols.reference.SymbolReferencesSearch.processQuery(SymbolReferencesSearch.java:23)
    at com.intellij.openapi.application.QueryExecutorBase.execute(QueryExecutorBase.java:79)
    at com.intellij.util.ExecutorsQuery.processResults(ExecutorsQuery.java:45)
    at com.intellij.util.AbstractQuery.forEach(AbstractQuery.java:75)
    at com.intellij.util.UniqueResultsQuery.process(UniqueResultsQuery.java:66)
    at com.intellij.util.UniqueResultsQuery.forEach(UniqueResultsQuery.java:56)
    at com.intellij.find.findUsages.FindUsagesHandler.processElementUsages(FindUsagesHandler.java:126)
    at com.intellij.find.findUsages.FindUsagesManager$2.generate(FindUsagesManager.java:376)
    at com.intellij.usages.impl.SearchForUsagesRunnable.searchUsages(SearchForUsagesRunnable.java:346)
    at com.intellij.usages.impl.SearchForUsagesRunnable.run(SearchForUsagesRunnable.java:325)
    at com.intellij.usages.impl.UsageViewManagerImpl$1.run(UsageViewManagerImpl.java:131)
    at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
    at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
    at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
    at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
    at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
    at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:366)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
    at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
```

Please let me know if additional details are required.

(OT: Thank you for this very useful plugin!)

**Comment by ziolko** [comment]
Hi @ThomasR,

Thank you for this bug report. I will take a look at this tomorrow and hopefully I will release a fix then :)

Have a nice day,
Mateusz

**Comment by ziolko** [comment]
Hi @ThomasR,

Unfortunately I wasn't able to reproduce this issue, but the error message is pretty clear about the root cause. I've released a new version with fix and hopefully it will work well now.

Please let me know if the new version works for you :)

Kind Regards,
Mateusz

**Comment by ThomasR** [comment]
Thanks for the quick fix! I'll try that in the next couple of days.

**Comment by ThomasR** [comment]
So I haven't experienced any errors lately. Good job!
